name: 'Github Api Checkout'
description: 'Checkout Github files by Github Api'
author: 'Cheng Huang'
inputs:
  repository:
    description: Repository
    required: true
  out-directory:
    description: Out directory
    required: false
    default: "."
  paths:
    description: Checkout files/folders
    required: true
  github-token:
    description: Github token
    required: true
  refs:
    description: Github ref / hash
    required: false
    default: ''

runs:
  using: 'node16'
  main: 'dist/index.js'
